applicationSet:
 metrics:
   enabled: true
   serviceMonitor:
     enabled: true

application:
 metrics:
   enabled: true
   serviceMonitor:
     enabled: true
     
dex-server:
  metrics:
   enabled: true
   serviceMonitor:
     enabled: true

notifications-controller:
 metrics:
   enabled: true
   serviceMonitor:
     enabled: true


redis:
 metrics:
   enabled: true
   serviceMonitor:
     enabled: true
   
repo-server:
 metrics:
   enabled: true
   serviceMonitor:
     enabled: true
server:
 metrics:
   enabled: true
   serviceMonitor:
     enabled: true
     